dist: xenial
group: bluezone

env:
    process.env.CI : false

before_install:
  - npm i -g npm@6.9.0

install:
  - npm install
  - npm run build-client

script:
  # Provide permissions to files
  - chmod 755 deploy/releaseToStaging.sh
  - chmod 755 deploy/releaseToDev.sh

  # Define the production tag
  - productionBuild=false;
  - if [ $TRAVIS_REPO_SLUG == 'IBM/ipm-marketplace-app' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then export productionBuild=true; fi

  - if [ $productionBuild == "true" ] && [ $TRAVIS_BRANCH == "master" ]; then . deploy/releaseToStaging.sh commerce-platform m-serviceaggregator-stage https://api.ng.bluemix.net mybluemix.net ipm-marketplace-app-stage ipm-marketplace-app-stage; fi

  - if [ $productionBuild == "true" ] && [ $TRAVIS_BRANCH == "dev" ]; then . deploy/releaseToDev.sh commerce-platform m-serviceaggregator-stage https://api.ng.bluemix.net mybluemix.net ipm-marketplace-app-dev ipm-marketplace-app-dev; fi

